### PR TITLE
fixes oracle tools install

### PR DESCRIPTION
**Pull request by SolidOceanTrust**
updates install_oracle_guest_addtions.ps1 to reflect new cert names in vbox

### CODE REVIEW

**Comment by MattHodge** [comment]
Hi @SolidOceanTrust - thanks for the pull request.

What do you think about changing the logic to check if the certificate exists on the `E:\` first using `Test-Path`, and if it does, adding to the store with `certutil -addstore`?

This would enable people with the old version of the Virtualbox tools to still continue to function.

**Comment by SolidOceanTrust** [comment]
That makes ALOT more sense than what I wrote. So you're thinking something like:
If ((test-path -Path E:\ -Filter *.cer))
{
    Get-ChildItem -Path E:\ -Filter *.cer | Foreach{ certutil -addstore -f "TrustedPublisher" $_}
}

**Comment by SolidOceanTrust** [comment]
if(test-path g:\ -Filter *.cer)
{
     Get-ChildItem G:\cert -Filter *.cer | Foreach {certutil -addstore -f "TrustedPublisher" $_.FullName } 
}

**Comment by MattHodge** [comment]
Yep, the last one looks good :) that way it can be future proof too :+1:

**Pull request merged**
